# Generated file that can be used to preload variant images
set(BOARD phyphox_satellite CACHE INTERNAL "NCS child image controlled")
set(BOARD_ROOT f:/Code/phyphox-Satellite-main/phyphox-Satellite-main;F:/Code/phyphox-Satellite-main/phyphox-Satellite-main;C:/Users/edwar/ncs/v1.9.1/nrf;C:/Users/edwar/ncs/v1.9.1/zephyr CACHE INTERNAL "NCS child image controlled")
set(CACHED_CONF_FILE f:/Code/phyphox-Satellite-main/phyphox-Satellite-main/prj.conf CACHE INTERNAL "NCS child image controlled")
set(CONFIG_DEBUG_OPTIMIZATIONS y CACHE INTERNAL "NCS child image controlled")
set(CONFIG_DEBUG_THREAD_INFO y CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE satellite.overlay CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE satellite.overlay CACHE INTERNAL "NCS child image controlled")
set(NCS_TOOLCHAIN_VERSION NONE CACHE INTERNAL "NCS child image controlled")
set(WEST_PYTHON c:\Users\edwar\ncs\v1.9.1\toolchain\opt\bin\python.exe CACHE INTERNAL "NCS child image controlled")
